# File: docker-compose.deploy.yml

version: '3.8'
services:
  nginx:
    # We have hardcoded the tag. No more variables!
    image: $autonmisiacrpoc.azurecr.io/nginx:11c483d7dbdfd9578b2303098531cb70534dd220
    ports:
      - "80:80"
    depends_on:
      - frontend
      - data-api
      - status-api
      - action-api

  frontend:
    image: $autonmisiacrpoc.azurecr.io/frontend:11c483d7dbdfd9578b2303098531cb70534dd220
  
  data-api:
    image: $autonmisiacrpoc.azurecr.io/data-api:11c483d7dbdfd9578b2303098531cb70534dd220

  status-api:
    image: $autonmisiacrpoc.azurecr.io/status-api:11c483d7dbdfd9578b2303098531cb70534dd220
  
  action-api:
    image: $autonmisiacrpoc.azurecr.io/action-api:11c483d7dbdfd9578b2303098531cb70534dd220