# File: docker-compose.prod.yml (Final Version)

version: '3.8'
services:
  nginx:
    image: ${ACR_LOGIN_SERVER}/nginx:${TAG}
    ports:
      - "80:80"
    depends_on:
      - frontend
      - data-api
      - status-api
      - action-api

  frontend:
    image: ${ACR_LOGIN_SERVER}/frontend:${TAG}
  
  data-api:
    image: ${ACR_LOGIN_SERVER}/data-api:${TAG}

  status-api:
    image: ${ACR_LOGIN_SERVER}/status-api:${TAG}
  
  action-api:
    image: ${ACR_LOGIN_SERVER}/action-api:${TAG}